remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      toc: true
      toc_label: "INDEX"
      toc_sticky: true
      toc_levels: 1..4
