remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      toc: true
      toc_label: "INDEX"
      toc_sticky: true
      toc_levels: 1..4
